// mutations

export const CLOSE_DRIVER_INFO = 'CLOSE_DRIVER_INFO';
export const SET_DRIVER_FOR_SHOWING_INFO = 'SET_DRIVER_FOR_SHOWING_INFO';
export const SET_DRIVER_INFO_VISIBILITY = 'SET_DRIVER_INFO_VISIBILITY';
export const SET_SELECTED_DRIVER = 'SET_SELECTED_DRIVER';
export const SET_BOOKING_NOTIFY_MODAL_VISIBILITY = 'SET_BOOKING_NOTIFY_MODAL_VISIBILITY';
export const SET_CURRENT_PREPARED_TRIP = 'SET_CURRENT_PREPARED_TRIP';

// actions
export const showClickedDriver = 'showClickedDriver';
